services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_main
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3,dynamodb,apigateway
      - LAMBDA_EXECUTOR=docker-reuse
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - PERSISTENCE=1
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: bridge
